Fun with simulators

diff --git a/.github/workflows/xcodebuild-or-fastlane.yml b/.github/workflows/xcodebuild-or-fastlane.yml
--- a/.github/workflows/xcodebuild-or-fastlane.yml
+++ b/.github/workflows/xcodebuild-or-fastlane.yml
@@ -32,15 +32,15 @@ on:
         type: string
         default: ''
       destination:
-        description: 'The destination parameter that should be passed to xcodebuild. Defaults to the iOS simulator using an iPhone 15 Pro'
+        description: 'The destination parameter that should be passed to xcodebuild. Defaults to the iOS simulator using an iPhone 15 Pro Simulator'
         required: false
         type: string
-        default: 'platform=iOS Simulator,name=iPhone 15 Pro'
+        default: 'platform=iOS Simulator,name=iPhone 15 Pro Simulator'
       setupSimulators:
         description: 'Flag indicating if all iOS simulators matching the `destination` input shoud be setup (e.g. password autofill functionality should be disabled).'
         required: false
         type: boolean
-        default: true
+        default: false
       resultBundle:
         description: 'The name of the Xcode result bundle that is passed to xcodebuild. If not defined, the name of the scheme + .xcresult is used.'
         required: false
@@ -236,7 +236,7 @@ jobs:
         parse_device_name() {
             local input_str=$1
             local IFS=',' # Set Internal Field Separator to comma for splitting
-
+            
             for kv in $input_str; do
                 key="${kv%%=*}"     # Extract key (everything before '=')
                 value="${kv#*=}"    # Extract value (everything after '=')
@@ -248,19 +248,11 @@ jobs:
             done
         }
 
-        # Function to check if a simulator is running
-        is_simulator_running() {
-            local simulator_id=$1
-            xcrun simctl list devices | grep -E "$simulator_id \(Booted\)" &> /dev/null
-            return $?
-        }
-
-        # Extract device name from the input (assuming it's passed as the first argument)
-        input=${1:-"platform=iOS Simulator,name=iPhone 15 Pro"}
-        DEVICE_NAME=$(parse_device_name "$input")
+        # Extract device name from the input
+        DEVICE_NAME=$(parse_device_name "${{ inputs.destination }}")
 
         echo "Device name: $DEVICE_NAME"
-
+        
         # Retrieve the iOS simulator IDs for the specified device
         SIMULATOR_IDS=$(xctrace list devices | grep "$DEVICE_NAME" | awk '{print $NF}' | tr -d '()')
 
@@ -274,17 +266,37 @@ jobs:
         for SIMULATOR_ID in $SIMULATOR_IDS; do
             echo "Processing Simulator ID: $SIMULATOR_ID"
 
-            # Disable AutoFillPasswords
-            plutil -replace restrictedBool.allowPasswordAutoFill.value -bool NO ~/Library/Developer/CoreSimulator/Devices/$SIMULATOR_ID/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles/Library/ConfigurationProfiles/UserSettings.plist
-            plutil -replace restrictedBool.allowPasswordAutoFill.value -bool NO ~/Library/Developer/CoreSimulator/Devices/$SIMULATOR_ID/data/Library/UserConfigurationProfiles/EffectiveUserSettings.plist
-            plutil -replace restrictedBool.allowPasswordAutoFill.value -bool NO ~/Library/Developer/CoreSimulator/Devices/$SIMULATOR_ID/data/Library/UserConfigurationProfiles/PublicInfo/PublicEffectiveUserSettings.plist
+            xcrun simctl boot "$SIMULATOR_ID"
 
-            # Check if the simulator is running and shut it down if it is
-            if is_simulator_running "$SIMULATOR_ID"; then
-                echo "Shutting down simulator $SIMULATOR_ID."
-                xcrun simctl shutdown "$SIMULATOR_ID"
+            PLIST1="$HOME/Library/Developer/CoreSimulator/Devices/$SIMULATOR_ID/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles/Library/ConfigurationProfiles/UserSettings.plist"
+            PLIST2="$HOME/Library/Developer/CoreSimulator/Devices/$SIMULATOR_ID/data/Library/UserConfigurationProfiles/EffectiveUserSettings.plist"
+            PLIST3="$HOME/Library/Developer/CoreSimulator/Devices/$SIMULATOR_ID/data/Library/UserConfigurationProfiles/PublicInfo/PublicEffectiveUserSettings.plist"
+
+            # Loop for a maximum of 30 seconds
+            for (( i=0; i<30; i++ )); do
+                if [ -f "$PLIST1" ] && [ -f "$PLIST2" ] && [ -f "$PLIST3" ]; then
+                    echo "All files found."
+                    break
+                fi
+                sleep 1
+            done
+
+            # Check if the loop exited because all files were found or because of timeout
+            if [ ! -f "$PLIST1" ] || [ ! -f "$PLIST2" ] || [ ! -f "$PLIST3" ]; then
+                echo "Error: Not all files were found within the 30-second timeout."
+                exit 1
+            fi
+
+            # Disable AutoFillPasswords
+            plutil -replace restrictedBool.allowPasswordAutoFill.value -bool NO $PLIST1
+            plutil -replace restrictedBool.allowPasswordAutoFill.value -bool NO $PLIST2
+            plutil -replace restrictedBool.allowPasswordAutoFill.value -bool NO $PLIST3
+
+            # Restart (shutdown if needed and boot) the iOS simulator for the changes to take effect
+            if xcrun simctl shutdown "$SIMULATOR_ID"; then
+                echo "Simulator $SIMULATOR_ID shutdown successfully."
             else
-                echo "Simulator $SIMULATOR_ID is already shutdown."
+                echo "Unable to shutdown simulator $SIMULATOR_ID as it is already shutdown."
             fi
         done
     - name: Run custom command
